/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package d0427;

import java.io.*;
import javax.swing.JOptionPane;
/**
 *
 * @author master
 */


public class JFrame0427 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame0427
     */
    public JFrame0427() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        dimtype = new javax.swing.JComboBox<>();
        createDxf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnBlkSz = new javax.swing.JButton();
        lsz = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cflutetype = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        wsz = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dsz = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFilePathName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        blksz = new javax.swing.JLabel();
        r2r2upint = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbSlotType = new javax.swing.JComboBox<>();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("d0427");

        dimtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID: Internal Dimensions", "BB: Bend to Bend", "OD: Outside Dimensions" }));
        dimtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimtypeActionPerformed(evt);
            }
        });

        createDxf.setText("Create DXF Drawing");
        createDxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDxfActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Dim Type:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0427", "0421", "0422" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Style:");

        btnBlkSz.setText("Calc Blank Size");
        btnBlkSz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlkSzActionPerformed(evt);
            }
        });

        lsz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lszActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Pack Size:");

        cflutetype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "B", "C", "BC", "Carton Brd" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Flute:");

        jLabel5.setText("x");

        jLabel6.setText("x");

        txtFilePathName.setText("drw0427.dxf");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("File Name:");

        blksz.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        blksz.setText("1up Blank Size:");

        r2r2upint.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        r2r2upint.setText("Interlock:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Slot:");

        cmbSlotType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rounded Ends", "Square Ends", "U Cut" }));
        cmbSlotType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSlotTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(createDxf, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBlkSz, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(r2r2upint, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blksz, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lsz, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wsz, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dsz, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cflutetype, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFilePathName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(dimtype, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSlotType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dimtype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lsz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(wsz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(dsz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtFilePathName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cflutetype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbSlotType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(blksz)
                .addGap(18, 18, 18)
                .addComponent(r2r2upint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBlkSz, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createDxf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public double idLength = 0;
  public double idWidth = 0;
  public double idDepth = 0;
  public double odLength = 0;
  public double odWidth = 0;
  public double odDepth = 0;
  // end attributes
  
    private void lszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lszActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lszActionPerformed

    private void btnBlkSzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlkSzActionPerformed
    this.getSizes();  // Get ID / OD sizes  
    draw0427cls oDxf = new draw0427cls();
    oDxf.unit = "M";
    oDxf.flute = (String) cflutetype.getSelectedItem();
    oDxf.length = this.idLength;
    oDxf.width = this.idWidth;
    oDxf.depth = this.idDepth;
    
    oDxf.allowanceSetup();
    
    System.out.println("1up Blank Size: " + oDxf.blks1 +  " x " + oDxf.blkn2 + "**" + oDxf.blks1IntLk);  
    BoardSz oMc = new BoardSz();
    oMc.blkS1 = oDxf.blks1;
    oMc.blkN2 = oDxf.blkn2;
    oMc.blkInsetN2 = oDxf.blkn2; //375;
    oMc.blkInsetS1 = oDxf.blks1IntLk; //350;
    oMc.diecutter = "Elite";
    oMc.asymmetrical = false;
    String msg = oMc.CalcR2R();
    
    blksz.setText("1up Blank Size: " + oDxf.blks1 +  " x " + oDxf.blkn2); 
    //r2r2upint.setText("INTERLOCK: " +  + oDxf.noUpS1 + "up " + oDxf.interlockblks1 + " x " + oDxf.interlockblkn2 + " " + oDxf.noUpN2 + "up");
    r2r2upint.setText(msg);
    
    // r2r2upint.setText("INTERLOCK: " +  + oDxf.noUpS1 + "up " + oDxf.interlockblks1 + " x " + oDxf.interlockblkn2 + " " + oDxf.noUpN2 + "up");

    }//GEN-LAST:event_btnBlkSzActionPerformed

    private void createDxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDxfActionPerformed
    this.getSizes();  // Get ID / OD sizes  
    String outputDxfData = "";   
    
    draw0427cls oDxf = new draw0427cls();
    
    oDxf.xabs = 0;
    oDxf.yabs = 0;
    oDxf.length = this.idLength;
    oDxf.width = this.idWidth;
    oDxf.depth = this.idDepth;
    
    int slotVal = 0; // Rounded Ends
    if (this.cmbSlotType.getSelectedItem().toString() == "Square Ends") {
        slotVal = 1; // Square Ends
    } else if (this.cmbSlotType.getSelectedItem().toString() == "U Cut") {
        slotVal = 2; // U Cut
    } 
    oDxf.slotType = slotVal;
    
    oDxf.unit = "M";
    oDxf.style = "";
    oDxf.flute = (String) cflutetype.getSelectedItem();
    oDxf.cutlay = "CUT";
    oDxf.crelay = "CREASE";
    oDxf.dxf = ""; // Output File's contents
    oDxf.dxfxmax = "0";
    oDxf.dxfymax = "0";
    
    oDxf.Xaxis = 1; // Direction of X axis +1 or -1
    oDxf.Yaxis = 1; // Direction of Y axis +1 or -1
    oDxf.allowanceSetup();
    
    outputDxfData = oDxf.Draw0427();
    
    String outputDir = ""; // "/home/tim/NetBeansProjects/T0427/src/t0427/"; // "../temp/";
    File f = new File(outputDir + txtFilePathName.getText());
    if(f.exists() && !f.isDirectory()) { 
      f.delete();
    }
    String outputDxfFile = outputDir + txtFilePathName.getText(); // "testfilel.dxf"; // "/var/www/temp/testfilel.dxf";
    
    BufferedWriter writer = null; // Note outside try block
    try {
      //create a file
      File newDxfFile = new File(outputDxfFile);
      
      writer = new BufferedWriter(new FileWriter(newDxfFile));
      writer.write(outputDxfData);
      writer.flush();
    } catch (Exception e) {
      e.printStackTrace();
    } finally {
      try {
        // Close the writer regardless of what happens...
        writer.close();
      } catch (Exception e) {
      }
    }
    
    JOptionPane.showMessageDialog(null, "Saved: " + outputDxfFile); 
    }//GEN-LAST:event_createDxfActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void cmbSlotTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSlotTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSlotTypeActionPerformed

    private void dimtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimtypeActionPerformed

    
  public void getSizes() {
    double l = Double.parseDouble(lsz.getText());
    double w = Double.parseDouble(wsz.getText());
    double d = Double.parseDouble(dsz.getText());
    double lengthPlus = 0; // Bulge Figures
    double widthPlus = 0;
    double depthPlus = 0;
    // Get Allowances
    draw0427cls oDxf = new draw0427cls();
    oDxf.length = 0;
    oDxf.width = 0;
    oDxf.depth = 0;
    oDxf.flute = (String) cflutetype.getSelectedItem();
    oDxf.allowanceSetup();
    
    if (dimtype.getSelectedItem() == "ID: Internal Dimensions") {
      this.idLength = l; 
      this.idWidth = w;
      this.idDepth = d;   
    } else if (dimtype.getSelectedItem() == "OD: Outside Dimensions") {      
      if (cflutetype.getSelectedItem().toString() == "B") {   // put Bulge figres here later if necessary
      } else if(cflutetype.getSelectedItem().toString() == "C") {
      } else if(cflutetype.getSelectedItem().toString() == "BC") {  
      } else { // E flute  
      } // end if  
      this.idLength = l - oDxf.l1 - oDxf.dmain - lengthPlus; // Assumes TOE section is Size given - dmain is the board Caliper here
      this.idWidth = w - oDxf.w2 - oDxf.dmain - widthPlus;  // dmain is the board Caliper here
      this.idDepth = d - oDxf.dmain - oDxf.dmain - depthPlus;
      
    } else { // Bend to Bend
      this.idLength = l - oDxf.l1; // dmain is the board Caliper here
      this.idWidth = w - oDxf.w1;
      this.idDepth = d - oDxf.dmain;      
    } 
    // Find O/D
    this.odLength = this.idLength + oDxf.l1 + oDxf.dmain + lengthPlus; // dmain is the board Caliper here
    this.odWidth = this.idWidth + oDxf.w2 + oDxf.dmain + widthPlus;
    this.odDepth = this.idDepth + oDxf.dmain + oDxf.dmain + depthPlus;
    
    parcelSizes oBjt = new parcelSizes();
    oBjt.odLength = this.odLength;
    oBjt.odWidth = this.odWidth;
    oBjt.odDepth = this.odDepth;
    oBjt.checkSizes();
    
  } // getSizes
 
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame0427.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame0427.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame0427.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame0427.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame0427().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blksz;
    private javax.swing.JButton btnBlkSz;
    private javax.swing.JComboBox<String> cflutetype;
    private javax.swing.JComboBox<String> cmbSlotType;
    private javax.swing.JButton createDxf;
    private javax.swing.JComboBox<String> dimtype;
    private javax.swing.JTextField dsz;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lsz;
    private javax.swing.JLabel r2r2upint;
    private javax.swing.JTextField txtFilePathName;
    private javax.swing.JTextField wsz;
    // End of variables declaration//GEN-END:variables
}
